[general]
# working_directory = "~/repos"     <-- doesn't support ~ yet
live_config_reload = true

[env]
TERMINAL_EMULATOR = "alacritty"

[window]
dimensions = { columns = 130, lines = 50 }
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "None"
opacity = 0.98
blur = true
startup_mode = "Windowed"
resize_increments = true

[scrolling]
history = 30000
multiplier = 5

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14

[colors]
[colors.primary]
foreground = "#D5E3E6"
background = "#131b20"

[colors.normal]
black = "#1c1c1c"
red = "#DC322F"
green = "#5DB016"
yellow = "#DF7C07"
blue = "#268BD2"
magenta = "#D33682"
cyan = "#924FC6"
white = "#EEE8D5"

[colors.bright]
black = "#2d2d2d"
red = "#e35c59"
green = "#86e633"
yellow = "#f9a034"
blue = "#5ba9e1"
magenta = "#dd649f"
cyan = "#b180d6"
white = "#f9f7f1"

[colors.dim]
black = "#0c0c0c"
red = "#831816"
green = "#2c520a"
yellow = "#945405"
blue = "#185581"
magenta = "#922057"
cyan = "#5f2c87"
white = "#dacea4"

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_timeout = 0
unfocused_hollow = true
thickness = 0.1

[terminal]
shell = "/usr/bin/zsh"

[debug]
render_timer = false
